#!/bin/sh

# Set default WiFi SSID and password
uci set wireless.radio0.disabled='0'
uci set wireless.default_radio0.ssid='www.anyfq.com'
uci set wireless.default_radio0.encryption='psk2'
uci set wireless.default_radio0.key='www.anyfq.com'

# Enable 5GHz radio if exists
[ -n "$(uci get wireless.radio1 2>/dev/null)" ] && {
	uci set wireless.radio1.disabled='0'
	uci set wireless.default_radio1.ssid='www.anyfq.com'
	uci set wireless.default_radio1.encryption='psk2'
	uci set wireless.default_radio1.key='www.anyfq.com'
}

# Enable all radios
for radio in $(uci show wireless | grep "^wireless.radio" | cut -d. -f2); do
	uci set wireless.$radio.disabled='0'
done

# Set default WiFi for all interfaces
for iface in $(uci show wireless | grep "=wifi-iface" | cut -d= -f1 | sed 's/wireless.//'); do
	uci set wireless.$iface.ssid='www.anyfq.com'
	uci set wireless.$iface.encryption='psk2'
	uci set wireless.$iface.key='www.anyfq.com'
done

uci commit wireless
/etc/init.d/network reload

exit 0
